src/Entity/Betaal.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BetaalRepository")
 */
class Betaal
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $soort;

    /**
     * @ORM\Column(type="date")
     */
    private $betaal_datum;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Reservering", mappedBy="betaalid", cascade={"persist", "remove"})
     */
    private $reservering;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $rekeningnummer;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSoort(): ?string
    {
        return $this->soort;
    }

    public function setSoort(string $soort): self
    {
        $this->soort = $soort;

        return $this;
    }

    public function getBetaalDatum(): ?\DateTimeInterface
    {
        return $this->betaal_datum;
    }

    public function setBetaalDatum(\DateTimeInterface $betaal_datum): self
    {
        $this->betaal_datum = $betaal_datum;

        return $this;
    }

    public function getReservering(): ?Reservering
    {
        return $this->reservering;
    }

    public function setReservering(Reservering $reservering): self
    {
        $this->reservering = $reservering;

        // set the owning side of the relation if necessary
        if ($this !== $reservering->getBetaalid()) {
            $reservering->setBetaalid($this);
        }

        return $this;
    }

    public function getRekeningnummer(): ?string
    {
        return $this->rekeningnummer;
    }

    public function setRekeningnummer(string $rekeningnummer): self
    {
        $this->rekeningnummer = $rekeningnummer;

        return $this;
    }

    public function __toString()
    {
        return strval($this->id);
    }

}

src/Form/BetaalType.php
<?php

namespace App\Form;

use App\Entity\Betaal;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BetaalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('soort')
            ->add('betaal_datum')
            ->add('rekeningnummer')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Betaal::class,
        ]);
    }
}

src/Controller/BetaalController.php
<?php

namespace App\Controller;

use App\Entity\Betaal;
use App\Form\BetaalType;
use App\Repository\BetaalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/betaal")
 */
class BetaalController extends AbstractController
{
    /**
     * @Route("/", name="betaal_index", methods={"GET"})
     */
    public function index(BetaalRepository $betaalRepository): Response
    {
        return $this->render('betaal/index.html.twig', [
            'betaals' => $betaalRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="betaal_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $betaal = new Betaal();
        $form = $this->createForm(BetaalType::class, $betaal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($betaal);
            $entityManager->flush();

            return $this->redirectToRoute('betaal_index');
        }

        return $this->render('betaal/new.html.twig', [
            'betaal' => $betaal,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="betaal_show", methods={"GET"})
     */
    public function show(Betaal $betaal): Response
    {
        return $this->render('betaal/show.html.twig', [
            'betaal' => $betaal,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="betaal_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Betaal $betaal): Response
    {
        $form = $this->createForm(BetaalType::class, $betaal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('betaal_index', [
                'id' => $betaal->getId(),
            ]);
        }

        return $this->render('betaal/edit.html.twig', [
            'betaal' => $betaal,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="betaal_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Betaal $betaal): Response
    {
        if ($this->isCsrfTokenValid('delete'.$betaal->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($betaal);
            $entityManager->flush();
        }

        return $this->redirectToRoute('betaal_index');
    }
}

templates/betaal/_delete_form.html.twig
<form method="post" action="{{ path('betaal_delete', {'id': betaal.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ betaal.id) }}">
    <button class="btn">Delete</button>
</form>

templates/betaal/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form)}}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/betaal/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Betaal{% endblock %}

{% block body %}
    <h1>Edit Betaal</h1>

    {{ include('betaal/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('betaal_index') }}">back to list</a>

    {{ include('betaal/_delete_form.html.twig') }}
{% endblock %}

templates/betaal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Betaal index{% endblock %}

{% block body %}
    <h1>Betaal index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Soort</th>
                <th>Betaal_datum</th>
                <th>Rekeningnummer</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for betaal in betaals %}
            <tr>
                <td>{{ betaal.id }}</td>
                <td>{{ betaal.soort }}</td>
                <td>{{ betaal.betaalDatum ? betaal.betaalDatum|date('Y-m-d') : '' }}</td>
                <td>{{ betaal.rekeningnummer }}</td>
                <td>
                    <a href="{{ path('betaal_show', {'id': betaal.id}) }}">show</a>
                    <a href="{{ path('betaal_edit', {'id': betaal.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('betaal_new') }}">Create new</a>
{% endblock %}

templates/betaal/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Betaal{% endblock %}

{% block body %}
    <h1>Create new Betaal</h1>

    {{ include('betaal/_form.html.twig') }}

    <a href="{{ path('betaal_index') }}">back to list</a>
{% endblock %}

templates/betaal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Betaal{% endblock %}

{% block body %}
    <h1>Betaal</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ betaal.id }}</td>
            </tr>
            <tr>
                <th>Soort</th>
                <td>{{ betaal.soort }}</td>
            </tr>
            <tr>
                <th>Betaal_datum</th>
                <td>{{ betaal.betaalDatum ? betaal.betaalDatum|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Rekeningnummer</th>
                <td>{{ betaal.rekeningnummer }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('betaal_index') }}">back to list</a>

    <a href="{{ path('betaal_edit', {'id': betaal.id}) }}">edit</a>

    {{ include('betaal/_delete_form.html.twig') }}
{% endblock %}